# main.yml
---
- hosts: localhost
  become: false
  tasks:

    - name: Organizations
      import_tasks: organizations.yml

    - name: Teams
      import_tasks: teams.yml

    - name: Users
      import_tasks: users.yml

    - name: Roles
      import_tasks: roles.yml

    - name: Groups
      import_tasks: groups.yml
...
